### ISSUE TITLE
Header와 Body 구현

### ISSUE THREAD

**Issue by Dae-Hwa** [sanhee/java-was#8]
`Header`는 `RequestHeader`와 `ResponseHeader`로 이루어져 있다

- 헤더의 각 항목이 배열이 적절할지 평문이 적절할지 판단이 필요하다.

`Body` 는 데이터로 구성되어있다.

- 바디 내부에 타입을 어떻게 구성할지 생각해볼 필요가 있다.

![image](https://user-images.githubusercontent.com/24666330/112427973-d5a94200-8d7d-11eb-9527-d442ce30ce48.png)

**Comment by sanhee** [comment]
👍
